-- EFORM EXTERNAL CLIENTS 1ST - CUSTOMER
CREATE TABLE APPLICANT (
  ID NUMBER PRIMARY KEY NOT NULL,
  FIRSTNAME NVARCHAR2(30),
  LASTNAME NVARCHAR2(30),
  AGE NUMBER(2),
  EMAIL NVARCHAR2(255),
  PHONE_NUMBER NVARCHAR2(14),
  CREATE_DATE TIMESTAMP
);

-- EFORM EXTERNAL CLIENTS 2ND - WEB_BO
CREATE TABLE WEB_BO (
  ID NUMBER PRIMARY KEY NOT NULL,
  APPLICANT_ID NUMBER NOT NULL,
  STATUS NVARCHAR2(10) NOT NULL,
  CREATE_DATE TIMESTAMP,
  CONSTRAINT FK_APPLICANTID FOREIGN KEY("APPLICANT_ID") REFERENCES APPLICANT("ID")
);

CREATE TABLE MSTR_WEB_BO_STATUS (
  STATUS NVARCHAR2(15) NOT NULL,
  DESCRIPTION NVARCHAR2(50) NOT NULL,
  CONSTRAINT MSTR_WEB_BO_STATUS_UNIQUE UNIQUE (STATUS)
);

-- EFORM EXTERNAL CLIENTS 3RD - WEB_KYC
CREATE TABLE WEB_KYC (
  ID NUMBER PRIMARY KEY NOT NULL,
  FIELD_1 NVARCHAR2(10) NOT NULL,
  FIELD_2 NVARCHAR2(10) NOT NULL,
  CREATE_DATE TIMESTAMP,
  APPLICANT_ID NUMBER NOT NULL,
  CONSTRAINT FK_APPLICANTID2 FOREIGN KEY("APPLICANT_ID") REFERENCES APPLICANT("ID")
);

-- EFORM EXTERNAL CLIENTS 4TH - ON_DEMAND_KYC
CREATE TABLE ON_DEMAND_KYC (
  ID NUMBER PRIMARY KEY NOT NULL,
  FIELD_1 NVARCHAR2(10) NOT NULL,
  FIELD_2 NVARCHAR2(10) NOT NULL,
  CREATE_DATE TIMESTAMP,
  APPLICANT_ID NUMBER NOT NULL,
  CONSTRAINT FK_APPLICANTID3 FOREIGN KEY("APPLICANT_ID") REFERENCES APPLICANT("ID")
);

--EFORM EVENTS
CREATE TABLE DRL_ENGINE_EVENTS (
  ID NUMBER PRIMARY KEY NOT NULL,
  EVENT_TYPE_CODE NVARCHAR2(10) NOT NULL,
  CREATE_DATE TIMESTAMP
);

CREATE TABLE MSTR_DRL_EVENT_TYPE (
  EVENT_TYPE_CODE NVARCHAR2(15) NOT NULL,
  DESCRIPTION NVARCHAR2(50) NOT NULL,
  CONSTRAINT MSTR_DRL_EVENT_TYPE_UNIQUE UNIQUE (EVENT_TYPE_CODE)
);

CREATE SEQUENCE CUSTOMER_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE WEB_BO_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE WEB_KYC_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE ON_DEMAND_KYC_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;