--MSTR_WEB_BO_STATUS
Insert into MSTR_WEB_BO_STATUS (STATUS, DESCRIPTION) VALUES ('PS_REQUESTED', 'APPLICANT FORM ON PRE-SCREENING REQUEST');
Insert into MSTR_WEB_BO_STATUS (STATUS, DESCRIPTION) VALUES ('PS_COMPLETED', 'APPLICANT FORM ON PRE-SCREENING COMPLETED');
Insert into MSTR_WEB_BO_STATUS (STATUS, DESCRIPTION) VALUES ('PS_REJECTED', 'APPLICANT FORM ON PRE-SCREENING REJECTED');

--MSTR_DRL_EVENT_TYPE
Insert into MSTR_DRL_EVENT_TYPE (EVENT_TYPE_CODE, DESCRIPTION) VALUES ('APPLICANT', 'EVENT ORIGINATED FROM APPLICANT');
Insert into MSTR_DRL_EVENT_TYPE (EVENT_TYPE_CODE, DESCRIPTION) VALUES ('WEB_BO', 'EVENT ORIGINATED FROM WEB_BO');
Insert into MSTR_DRL_EVENT_TYPE (EVENT_TYPE_CODE, DESCRIPTION) VALUES ('WEB_KYC', 'EVENT ORIGINATED FROM WEB_KYC');
Insert into MSTR_DRL_EVENT_TYPE (EVENT_TYPE_CODE, DESCRIPTION) VALUES ('ON_DEMAND_KYC', 'EVENT ORIGINATED FROM ON_DEMAND_KYC');