DROP TABLE WEB_BO CASCADE CONSTRAINTS;
DROP TABLE MSTR_WEB_BO_STATUS CASCADE CONSTRAINTS;
DROP TABLE WEB_KYC CASCADE CONSTRAINTS;
DROP TABLE ON_DEMAND_KYC CASCADE CONSTRAINTS;
DROP TABLE DRL_ENGINE_EVENTS CASCADE CONSTRAINTS;
DROP TABLE MSTR_DRL_EVENT_TYPE CASCADE CONSTRAINTS;
DROP TABLE APPLICANT;

DROP SEQUENCE CUSTOMER_SEQ;
DROP SEQUENCE WEB_BO_SEQ;
DROP SEQUENCE WEB_KYC_SEQ;
DROP SEQUENCE ON_DEMAND_KYC_SEQ;